-- MySQL Script generated by MySQL Workbench
-- Τρι 12 Ιαν 2016 05:47:51 μμ EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `library` ;

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`User` ;

CREATE TABLE IF NOT EXISTS `library`.`User` (
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `isStudent` TINYINT(1) NOT NULL,
  `isAuthor` TINYINT(1) NOT NULL,
  `isPublisher` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`Author` ;

CREATE TABLE IF NOT EXISTS `library`.`Author` (
  `AuthorName` VARCHAR(45) NOT NULL,
  `AuthorUsername` VARCHAR(45) NULL,
  `Rating` INT NOT NULL,
  `Information` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`AuthorName`),
  CONSTRAINT `fk_Author_User1`
    FOREIGN KEY (`AuthorUsername`)
    REFERENCES `library`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`Publisher` ;

CREATE TABLE IF NOT EXISTS `library`.`Publisher` (
  `PublisherName` VARCHAR(45) NOT NULL,
  `PublisherUsername` VARCHAR(45) NULL,
  `Rating` INT NOT NULL,
  `Information` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`PublisherName`),
  CONSTRAINT `fk_Publisher_User1`
    FOREIGN KEY (`PublisherUsername`)
    REFERENCES `library`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`Book` ;

CREATE TABLE IF NOT EXISTS `library`.`Book` (
  `ISBN` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `YearOfPublish` VARCHAR(4) NOT NULL,
  `Rating` INT NOT NULL,
  `Description` VARCHAR(1000) NOT NULL,
  `isAvailable` TINYINT(1) NOT NULL,
  `isOnline` TINYINT(1) NOT NULL,
  `AuthorName` VARCHAR(45) NOT NULL,
  `PublisherName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN`, `AuthorName`, `PublisherName`),
  INDEX `fk_Book_Author1_idx` (`AuthorName` ASC),
  INDEX `fk_Book_Publisher1_idx` (`PublisherName` ASC),
  CONSTRAINT `fk_Book_Author1`
    FOREIGN KEY (`AuthorName`)
    REFERENCES `library`.`Author` (`AuthorName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_Publisher1`
    FOREIGN KEY (`PublisherName`)
    REFERENCES `library`.`Publisher` (`PublisherName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`Library` ;

CREATE TABLE IF NOT EXISTS `library`.`Library` (
  `Name` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(100) NOT NULL,
  `Address` VARCHAR(500) NOT NULL,
  `FAX` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Longitude` FLOAT NOT NULL,
  `Latitude` FLOAT NOT NULL,
  `Info` VARCHAR(1000) NOT NULL,
  `OpenInfro` VARCHAR(200) NOT NULL,
  `MainLibrary` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Library_has_Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`Library_has_Book` ;

CREATE TABLE IF NOT EXISTS `library`.`Library_has_Book` (
  `Library_Name` VARCHAR(100) NOT NULL,
  `Book_ISBN` INT NOT NULL,
  `NumOfCopies` INT NOT NULL,
  PRIMARY KEY (`Library_Name`, `Book_ISBN`),
  INDEX `fk_Library_has_Book_Book1_idx` (`Book_ISBN` ASC),
  INDEX `fk_Library_has_Book_Library_idx` (`Library_Name` ASC),
  CONSTRAINT `fk_Library_has_Book_Library`
    FOREIGN KEY (`Library_Name`)
    REFERENCES `library`.`Library` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Library_has_Book_Book1`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `library`.`Book` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`User_borrows_Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`User_borrows_Book` ;

CREATE TABLE IF NOT EXISTS `library`.`User_borrows_Book` (
  `User_Username` VARCHAR(45) NOT NULL,
  `Book_ISBN` INT NOT NULL,
  `ReturnDate` DATE NOT NULL,
  `BorrowDate` DATE NOT NULL,
  PRIMARY KEY (`User_Username`, `Book_ISBN`),
  INDEX `fk_User_has_Book_Book1_idx` (`Book_ISBN` ASC),
  INDEX `fk_User_has_Book_User1_idx` (`User_Username` ASC),
  CONSTRAINT `fk_User_has_Book_User1`
    FOREIGN KEY (`User_Username`)
    REFERENCES `library`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Book_Book1`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `library`.`Book` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
